Practica_ClaseSemana4/Models/ClsUsuario.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Practica_ClaseSemana4.Models
{
    public class ClsUsuario
    {
       public string nombre {get; set;}
       public string pass { get; set; }

    }
}

Practica_ClaseSemana4/Controllers/EmpleadoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Practica_ClaseSemana4.Controllers
{
    public class EmpleadoController : Controller
    {
        // GET: Empleado
        public ActionResult Empleado()
        {
            return View();
        }

        public ActionResult Recibo(String valorPorHora, String NombreEmpleado, String tiempoLabor, String horasDeTrabajo)
        {
            Double VporHora = Convert.ToDouble(valorPorHora);
            int time = Convert.ToInt32(tiempoLabor);
            int horasTrabajo = Convert.ToInt32(horasDeTrabajo);

            Double SueldoBruto = VporHora * time + horasTrabajo * 30;
            Double TotalDescuentos = ((VporHora * time + horasTrabajo * 30) * 0.13);
            Double SueldoConDescuentos = ((VporHora * time + horasTrabajo * 30) -
                                           (VporHora * time + horasTrabajo * 30) * 0.13);

            //Formularios: forma de traer la información de la vista hacia el back_ end

            //ViewBag : forma de llevar la información del back_ end hacia la vista

            ViewBag.nombre = NombreEmpleado;
            ViewBag.antiguedad= tiempoLabor;
            ViewBag.valorPHora = valorPorHora;
            ViewBag.SBruto = SueldoBruto;
            ViewBag.DesTotal = TotalDescuentos;
            ViewBag.SDesc= SueldoConDescuentos;

            return View();
        }
    }
    
}

Practica_ClaseSemana4/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Practica_ClaseSemana4.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Practica_ClaseSemana4/Controllers/UsuarioController.cs
using Practica_ClaseSemana4.DaoRe;
using Practica_ClaseSemana4.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Practica_ClaseSemana4.Controllers
{
    public class UsuarioController : Controller
    {
        // GET: Usuario
        public ActionResult Usuario()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Usuario (string Usuario, String Pass) {

            ClsUsuario ObjUsuario = new ClsUsuario();
            ObjUsuario.nombre = Usuario;
            ObjUsuario.pass = Pass;


            UsuarioRepository repository = new UsuarioRepository();


            for (int i = 0; i<repository.pass.Length; i++) {
            if(ObjUsuario.pass.Equals(repository.pass[0]) && ObjUsuario.nombre.Equals(repository.user[0])) {

                    //Dentro de una estructura condicional el método no lo detecta --- fuera de rango
                    return Redirect("/Empleado/Empleado");
                }
           }
            //Los métodos deben tener un return --- siempre 
            //sino se cumple la condición se retorna a la vista
            return View(); //retornar vista en la que se está
        }

    }   
}

Practica_ClaseSemana4/Views/Empleado/Empleado.cshtml
@{
    ViewBag.Title = "Acceso";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Recibo</h2>

@using (Html.BeginForm("Recibo", "Empleado"))
{
    //Nombre de los name igual al de los parametros en el controlador



    <div class="col-6">
        <label>Valor por hora:</label>
        <input type="text" class="form-control" name="valorPorHora" placeholder="Valor por hora $">
    </div>
    <div class="col-6">
        <label>Nombre empleado:</label>
        <input type="text" class="form-control" name="NombreEmpleado" placeholder="Ingrese su nombre completo">
    </div>
    <div class="col-6">
        <label>Años laborados :</label>
        <input type="text" class="form-control" name="tiempoLabor" placeholder="Años de servicio en la empresa">
    </div>

    <div class="col-6">
        <label>Horas trabajadas por mes :</label>
        <input type="text" class="form-control" name="horasDeTrabajo" placeholder="Horas de trabajo por mes">
    </div>


        <button type="submit" class="btn btn-primary">Continuar</button>
    

}


@*<label>Ingresa el valor por hora :</label>
    <input type="text" name="valorPorHora" />
    <br />

    <label>Nombre empleado :</label>
    <input type="text" name="NombreEmpleado" />
    <br />

    <label>Años laborados :</label>
    <input type="text" name="tiempoLabor" />
    <br />

    <label>Horas trabajadas por mes :</label>
    <input type="text" name="horasDeTrabajo" />
    <br />

    <input type="submit" />*@

Practica_ClaseSemana4/Views/Empleado/Recibo.cshtml
@{
    ViewBag.Title = "Recibo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Recibo</h2>

<table class="table table-bordered border-primary">
    <th>
        Nombre:
    </th>

    <th>
        Antiguedad :
    </th>

    <th>
        Valor por hora :
    </th>

    <th>
        Sueldo bruto :
    </th>
    <th>
        Sueldo con descuentos :
    </th>

    <th>
        Sueldo total :
    </th>


    <tbody>

        <tr>
            <td>@ViewBag.nombre</td>
            <td>@ViewBag.antiguedad</td>
            <td>@ViewBag.valorPHora</td>
            <td>@ViewBag.SBruto</td>
            <td>@ViewBag.SBruto</td>
            <td>@ViewBag.DesTotal</td>
            <td>@ViewBag.SDesc</td>
        </tr>

    </tbody>
</table>

Practica_ClaseSemana4/Views/Usuario/Usuario.cshtml
@*Esto equivale a using*@
@model List<Practica_ClaseSemana4.Models.ClsUsuario>
@{
    ViewBag.Title = "Usuario";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<center><h2>Bienvenidos</h2></center>

@*Tipo de petición*@
@*Acción/ Controlador*@
@using (Html.BeginForm("Usuario", "Usuario", FormMethod.Post))
{
    //Nombre de los name igual al de los parametros en el controlador
    <center>
        <div class="form-group" border=" 1">
            <label>Usuario</label>
            <input type="text" required placeholder="Escribe tu usuario" class="form-control" name="Usuario">
            <small name="Usuario" class="form-text text-muted">We'll never share your user with anyone else.</small>
        </div>
        <div class="form-group">
            <label>Contraseña</label>
            <input type="password" required placeholder="Escribe tu contraseña" class="form-control" name="Pass">
        </div>

        <button type="submit" class="btn btn-primary">Ingresar</button>
    </center>


}
@*<label>Ingresa tu usuario :</label>
    <input type="text" name="Usuario" />
    <br />

    <label>Ingresa tu contraseña :</label>
    <input type="text" name="Pass" />
    <br />

    <input type="submit" />*@